### ISSUE TITLE
Add Travis integration and build badges

### ISSUE THREAD

**Issue by katowulf** [firebase/angularfire-seed#56]
Let's get that build badge and Travis CI going for this repo. I don't think this will take a lot of work, especially since the `.travis.yml` file is already written.

**Comment by robotnoises** [comment]
See PR [#89](https://github.com/firebase/angularfire-seed/pull/89).

I just configured Travis for my own project, and since I used this repo as my seed I figured I'd pay it forward.

Thanks!

**Comment by jwngr** [comment]
Fixed with #89 / #91.
