### ISSUE TITLE
Cannot bower install

### ISSUE THREAD

**Issue by chinedufn** [firebase/angularfire-seed#63]
The new dependencies list calls for 0.9.1 angularfire and ~0.8.0 for mockfirebase.

Both projects seem have 0.9.0 and 0.7.0 as their latest versions, respectively.

0.9.0 and ~0.7.0 work as dependencies and bower install executes successfully.

**Comment by katowulf** [comment]
AF 0.9.1 is public and I've updated the seed deps as well. Cheers.
