### ISSUE TITLE
Issue with bower install

### ISSUE THREAD

**Issue by JesseWynants** [firebase/angularfire-seed#69]
Hi Guys,

When I cloned this package and ran "npm install" as stated in the readme, but it keeps failing on the postinstall step:

```
npm ERR! angularfire-seed@0.9.1 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angularfire-seed@0.9.1 postinstall script.
npm ERR! This is most likely a problem with the angularfire-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls angularfire-seed
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 13.4.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/Jesse/Sites/angularfire-seed
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/Jesse/Sites/angularfire-seed/npm-debug.log
npm ERR! not ok code 0
```
Any one any idea what this could be?

**Comment by simplydragons** [comment]
I've been having troubles with this as well - it seems to be an issue in npm that prevents it from spawning scripts like 'postinstall', etc. Try removing lines 18 and 20 in `package.json` and then running `npm install` followed by `bower install`. To start the server, you'll need to separately run `node_modules/http-server/bin/http-server -a localhost -p 8000`

The source of the npm problem appears to be similar to [this one](https://github.com/npm/npm/issues/5920), which is supposedly fixed but apparently not. You might find it useful to upgrade npm to the latest version (2.1.16), though that didn't fix it for me.

Let me know if this helps any, this is a frustrating issue.

**Comment by myhusam** [comment]
I got same issue and I guess the problem is from `bower install`.

`bower ENORESTARGET  No tag found that was able to satisfy 0.9.1`

When I changed the `angularfire` version to `0.9.0` it works!

**Comment by belgac** [comment]
I have the same problem under windows 7 changing the angularfire version to 0.9.0 in the bower.json file corrects it. Thanks a lot @myhusam

**Comment by katowulf** [comment]
Thanks, gents. All the package deps have been updated now with the 0.9.1 release.
