### ISSUE TITLE
Change the router to ui-router to better fit with hybrid app development

### ISSUE THREAD

**Issue by sibizavic** [firebase/angularfire-seed#72]
The Ionic Framework, which is targeting Hybrid App development, is using ui-router and not ngRoute. It would be helpful if the seed was updated with this router, since it will fit the needs better of Ionic users. Ionic + Angularfire = SUPER.

So example, instead of $routeProvider, use $stateProvider and $urlRouterProvider. See also these Stackoverflow threads:

http://stackoverflow.com/questions/27919135/can-routeprovider-be-replaced-by-stateprovider-or-vice-versa-and-how

http://stackoverflow.com/questions/27971565/how-to-replace-routeprovider-with-stateprovider

http://stackoverflow.com/questions/27967611/can-the-ionic-function-ion-nav-view-ui-router-work-with-ngroute

**Comment by katowulf** [comment]
This is not an ionic seed. While I recognize the usefulness of this idea, the angular-seed utilizes ngRoute and we'll follow suit until that is changed as well.
