### ISSUE TITLE
bower install error

### ISSUE THREAD

**Issue by chrislewispac** [firebase/angularfire-seed#77]
bower not-cached    git://github.com/angular/bower-angular-loader.git#~1.2.x
bower resolve       git://github.com/angular/bower-angular-loader.git#~1.2.x
bower not-cached    git://github.com/angular/bower-angular.git#~1.2.x
bower resolve       git://github.com/angular/bower-angular.git#~1.2.x
bower not-cached    git://github.com/angular/bower-angular-route.git#~1.2.x
bower resolve       git://github.com/angular/bower-angular-route.git#~1.2.x
bower not-cached    git://github.com/angular/bower-angular-mocks.git#~1.2.x
bower resolve       git://github.com/angular/bower-angular-mocks.git#~1.2.x
bower not-cached    git://github.com/firebase/angularFire.git#0.9.1
bower resolve       git://github.com/firebase/angularFire.git#0.9.1
bower not-cached    git://github.com/firebase/firebase-bower.git#2.0.x
bower resolve       git://github.com/firebase/firebase-bower.git#2.0.x
bower not-cached    git://github.com/h5bp/html5-boilerplate.git#~4.3.0
bower resolve       git://github.com/h5bp/html5-boilerplate.git#~4.3.0
bower not-cached    git://github.com/katowulf/mockfirebase.git#~0.8.0
bower resolve       git://github.com/katowulf/mockfirebase.git#~0.8.0
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github.com/angular/bower-angular-loader.git", exit code of #128

Additional error details:
fatal: unable to connect to github.com:
github.com[0: 192.30.252.128]: errno=Connection refused

npm ERR! angularfire-seed@0.9.1 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angularfire-seed@0.9.1 postinstall script.
npm ERR! This is most likely a problem with the angularfire-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls angularfire-seed
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/christopherlewis/PycharmProjects/angularfire-seed
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/christopherlewis/PycharmProjects/angularfire-seed/npm-debug.log
npm ERR! not ok code 0

**Comment by katowulf** [comment]
it says it couldn't connect to github.com. This doesn't look like an error in angularFire-seed?

> fatal: unable to connect to github.com:
> github.com[0: 192.30.252.128]: errno=Connection refused

**Comment by chrislewispac** [comment]
resolved. sorry....

**Comment by vivekmore** [comment]
@chrislewispac - I'm getting this error when I try to build an angular seed project 
```
git clone https://github.com/angular/angular-seed.git angular-tutorial
cd angular-tutorial
bower install 
```
Could you please help me understand how this was resolved when you encountered it ?
