### ISSUE TITLE
Using location path inside controller doesn't work

### ISSUE THREAD

**Issue by smoresch** [firebase/angularfire-seed#78]
Hi, i have started to develop an application using angularfire-seed. I have added one controller called controller1 and inside it i have one scope like this: 

 $scope.doRedirect = function() {
        $location.path('controller2');
 }

I have put controller2 inside my route file, html in partials e controller2 under js folder, but every time i call 'doRedirect' angular redirect me to home. Why?

**Comment by katowulf** [comment]
Can you explain how this is related to angularFire-seed and not just a question about ngRoute? I'm not positive this is the correct forum for your question. You've also not included sufficient information here to answer the question: where are the routes? How could we guess why the route is invalid without seeing them? Also, shouldn't it be /controller2?

**Comment by smoresch** [comment]
Sorry, just solved 1 minute ago, there was an error in my html page.
