### ISSUE TITLE
npm install / start fails

### ISSUE THREAD

**Issue by sdbeng** [firebase/angularfire-seed#80]
Hey guys,
I've just cloned the project and it failed to run npm start at the command line. 
Checked the file structure and it's missing the whole app/bower_components directory.
I did npm install one more time, and got this error:
sudo npm install
Password:
npm WARN package.json karma-firefox-launcher@0.1.4 No README data
npm WARN cannot run in wd angularfire-seed@0.9.1 bower install (wd=/Users/homedir/1-Angular2015/angularfire-seed)

As the previous closed issue (where bower fails), it has angularfire 0.9.1. 
Thanks for your advice.

**Comment by katowulf** [comment]
Hi there! Thanks for reaching out.

I'm not going to be able to help much here unless I can repro. Please send all the logs and version info, as well as output from `npm list -g --depth=0` and `npm list --depth=0`.

Cheers,
Kato

**Comment by sdbeng** [comment]
/usr/local/lib
├── bower@1.3.12
├── express@4.9.7
├── express-generator@4.9.0
├── firebase-tools@1.1.5
├── foundation-cli@1.0.3
├── generator-angular@0.11.1
├── generator-gulp-webapp@0.1.0
├── generator-karma@0.9.0
├── generator-meanjs@0.1.10
├── generator-mocha@0.1.5
├── generator-webapp@0.5.0
├── grunt-cli@0.1.13
├── gulp@3.8.10
├── http-server@0.6.1
├── npm@2.5.1
└── yo@1.4.5

angularfire-seed@0.9.1 /Users/admin/1-Angular2015/angularfire-seed
├── bower@1.3.12
├── http-server@0.6.1
├── karma@0.10.10
├── karma-chrome-launcher@0.1.7
├── karma-coffee-preprocessor@0.1.3
├── karma-firefox-launcher@0.1.4
├── karma-html2js-preprocessor@0.1.0
├── karma-jasmine@0.1.5
├── karma-junit-reporter@0.2.2
├── karma-phantomjs-launcher@0.1.4
├── karma-requirejs@0.2.2
├── karma-script-launcher@0.1.0
├── protractor@0.20.1
├── requirejs@2.1.16
└── shelljs@0.2.6

**Comment by katowulf** [comment]
Can't repro this. Please try the new 1.0.0 release if this error is still occurring.

**Comment by sdbeng** [comment]
Sure, will try the newer version and see how it goes. Tx

**Comment by katowulf** [comment]
Cheers, if you still have issues, let's get a more complete picture of your environment and setup so I can reopen and try to investigate.
