### ISSUE TITLE
Error when running "sudo npm start"

### ISSUE THREAD

**Issue by jtolla** [firebase/angularfire-seed#85]
The command fails in my environment and the following npm error log is generated.

    0 info it worked if it ends with ok
    1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
    2 info using npm@2.7.4
    3 info using node@v0.12.2
    4 verbose run-script [ 'prestart', 'start', 'poststart' ]
    5 info prestart angularfire-seed@1.0.0
    6 verbose unsafe-perm in lifecycle true
    7 info angularfire-seed@1.0.0 Failed to exec prestart script
    8 verbose stack Error: angularfire-seed@1.0.0 prestart: `npm install`
    8 verbose stack Exit status 243
    8 verbose stack     at EventEmitter.<anonymous>       (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
    8 verbose stack     at EventEmitter.emit (events.js:110:17)
    8 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
    8 verbose stack     at ChildProcess.emit (events.js:110:17)
    8 verbose stack     at maybeClose (child_process.js:1015:16)
    8 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
    9 verbose pkgid angularfire-seed@1.0.0
    10 verbose cwd /Users/jtolla/Projects/utm
    11 error Darwin 14.3.0
    12 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
    13 error node v0.12.2
    14 error npm  v2.7.4
    15 error code ELIFECYCLE
    16 error angularfire-seed@1.0.0 prestart: `npm install`
    16 error Exit status 243
    17 error Failed at the angularfire-seed@1.0.0 prestart script 'npm install'.
    17 error This is most likely a problem with the angularfire-seed package,
    17 error not with npm itself.
    17 error Tell the author that this fails on your system:
    17 error     npm install
    17 error You can get their info via:
    17 error     npm owner ls angularfire-seed
    17 error There is likely additional logging output above.
    18 verbose exit [ 1, true ]

**Comment by jtolla** [comment]
Noticed that the start script was "http-server -a localhost -p 8000", I didn't have http-server installed globally so I installed it. I'm now able to get the application running on the default port (8080), but still can't run the original "http-server -a localhost -p 8000" command without throwing an error.

**Comment by katowulf** [comment]
It shouldn't be necessary to install this globally. Details in the README: https://github.com/firebase/angularfire-seed#serving-the-application-files

**Comment by jtolla** [comment]
I saw that. I didn't try running plain old "http-server" from the project directory before I installed it globally. Only "http-server -a localhost -p 8000". Got it working anyway.

**Comment by katowulf** [comment]
Yay. Any advice you can add for others if they run into the same issue?

**Comment by jtolla** [comment]
Whoops. Didn't mean I got "http-server -a localhost -p 8000" working. That command still fails. I'm just running "http-server" from the project directory and everything is working just fine. Application is running on 8080.
