### ISSUE TITLE
Is this project still using simplelogin?

### ISSUE THREAD

**Issue by Telemakhos** [firebase/angularfire-seed#88]
I've noticed that this boilerplate creates the users as "simplelogin:xx" when using the Email & Password auth provider. Is this normal? Can we change this id's?

Sorry for the newbie questions!

Edit: Ok, I've just learnt in a SO thread that this is the default naming... but can it be changed?

**Comment by Telemakhos** [comment]
Ok, I've just learnt in a SO thread that this is the default naming... but can it be changed?

**Comment by katowulf** [comment]
I don't see simpleLogin anywhere in the main branch. https://github.com/firebase/angularfire-seed/tree/master/app/login

**Comment by katowulf** [comment]
Ah, the uids are generated by Firebase and use `simplelogin` for historical purposes. This is unrelated to the seed or AngularFire.

**Comment by Telemakhos** [comment]
Ok! Thanks for the clarification!
