### ISSUE TITLE
How do I login?

### ISSUE THREAD

**Issue by ix-xerri** [firebase/angularfire-seed#92]
Can you give me a username and password?

**Comment by katowulf** [comment]
Check out the README section on [Configuring The Application](https://github.com/firebase/angularfire-seed#configure-the-application). You need a Firebase instance name (e.g. https://<instance>.firebaseio.com), which you put into the File, and you need to enable authentication in your app. Once this is done, start up the app and click the `Create Account` button.

**Comment by ix-xerri** [comment]
everything works....it may help to make these steps a bit more prominent
